### ISSUE TITLE
Install is broken...

### ISSUE THREAD

**Issue by xxinfinityxx** [vikingco/django-multipleformwizard#2]
Hello there,

I tried installing your app but somehow it fails. See below:
```
 pip install django-multipleformwizard
Downloading/unpacking django-multipleformwizard
  Downloading django-multipleformwizard-0.2.12.tar.gz
  Running setup.py egg_info for package django-multipleformwizard
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/home/noss/.virtualenvs/noss/build/django-multipleformwizard/setup.py", line 7, in <module>
        import multipleformwizard
      File "multipleformwizard/__init__.py", line 5, in <module>
        from .views import (SessionMultipleFormWizardView, CookieMultipleFormWizardView,
      File "multipleformwizard/views.py", line 10, in <module>
        from django.shortcuts import redirect
      File "/home/noss/.virtualenvs/noss/lib/python2.7/site-packages/django/shortcuts/__init__.py", line 11, in <module>
        from django.db.models.base import ModelBase
      File "/home/noss/.virtualenvs/noss/lib/python2.7/site-packages/django/db/models/__init__.py", line 5, in <module>
        from django.db.models.query import Q
      File "/home/noss/.virtualenvs/noss/lib/python2.7/site-packages/django/db/models/query.py", line 17, in <module>
        from django.db.models.deletion import Collector
      File "/home/noss/.virtualenvs/noss/lib/python2.7/site-packages/django/db/models/deletion.py", line 4, in <module>
        from django.db.models import signals, sql
      File "/home/noss/.virtualenvs/noss/lib/python2.7/site-packages/django/db/models/sql/__init__.py", line 4, in <module>
        from django.db.models.sql.subqueries import *
      File "/home/noss/.virtualenvs/noss/lib/python2.7/site-packages/django/db/models/sql/subqueries.py", line 12, in <module>
        from django.db.models.sql.query import Query
      File "/home/noss/.virtualenvs/noss/lib/python2.7/site-packages/django/db/models/sql/query.py", line 22, in <module>
        from django.db.models.sql import aggregates as base_aggregates_module
      File "/home/noss/.virtualenvs/noss/lib/python2.7/site-packages/django/db/models/sql/aggregates.py", line 9, in <module>
        ordinal_aggregate_field = IntegerField()
      File "/home/noss/.virtualenvs/noss/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 116, in __init__
        self.db_tablespace = db_tablespace or settings.DEFAULT_INDEX_TABLESPACE
      File "/home/noss/.virtualenvs/noss/lib/python2.7/site-packages/django/conf/__init__.py", line 54, in __getattr__
        self._setup(name)
      File "/home/noss/.virtualenvs/noss/lib/python2.7/site-packages/django/conf/__init__.py", line 47, in _setup
        % (desc, ENVIRONMENT_VARIABLE))
    django.core.exceptions.ImproperlyConfigured: Requested setting DEFAULT_INDEX_TABLESPACE, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/home/noss/.virtualenvs/noss/build/django-multipleformwizard/setup.py", line 7, in <module>

    import multipleformwizard

  File "multipleformwizard/__init__.py", line 5, in <module>

    from .views import (SessionMultipleFormWizardView, CookieMultipleFormWizardView,

  File "multipleformwizard/views.py", line 10, in <module>

    from django.shortcuts import redirect

  File "/home/noss/.virtualenvs/noss/lib/python2.7/site-packages/django/shortcuts/__init__.py", line 11, in <module>

    from django.db.models.base import ModelBase

  File "/home/noss/.virtualenvs/noss/lib/python2.7/site-packages/django/db/models/__init__.py", line 5, in <module>

    from django.db.models.query import Q

  File "/home/noss/.virtualenvs/noss/lib/python2.7/site-packages/django/db/models/query.py", line 17, in <module>

    from django.db.models.deletion import Collector

  File "/home/noss/.virtualenvs/noss/lib/python2.7/site-packages/django/db/models/deletion.py", line 4, in <module>

    from django.db.models import signals, sql

  File "/home/noss/.virtualenvs/noss/lib/python2.7/site-packages/django/db/models/sql/__init__.py", line 4, in <module>

    from django.db.models.sql.subqueries import *

  File "/home/noss/.virtualenvs/noss/lib/python2.7/site-packages/django/db/models/sql/subqueries.py", line 12, in <module>

    from django.db.models.sql.query import Query

  File "/home/noss/.virtualenvs/noss/lib/python2.7/site-packages/django/db/models/sql/query.py", line 22, in <module>

    from django.db.models.sql import aggregates as base_aggregates_module

  File "/home/noss/.virtualenvs/noss/lib/python2.7/site-packages/django/db/models/sql/aggregates.py", line 9, in <module>

    ordinal_aggregate_field = IntegerField()

  File "/home/noss/.virtualenvs/noss/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 116, in __init__

    self.db_tablespace = db_tablespace or settings.DEFAULT_INDEX_TABLESPACE

  File "/home/noss/.virtualenvs/noss/lib/python2.7/site-packages/django/conf/__init__.py", line 54, in __getattr__

    self._setup(name)

  File "/home/noss/.virtualenvs/noss/lib/python2.7/site-packages/django/conf/__init__.py", line 47, in _setup

    % (desc, ENVIRONMENT_VARIABLE))

django.core.exceptions.ImproperlyConfigured: Requested setting DEFAULT_INDEX_TABLESPACE, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /home/noss/.virtualenvs/noss/build/django-multipleformwizard
Storing complete log in /home/noss/.pip/pip.log
```

Why is it trying to load django's settings ?

**Comment by dirkmoors** [comment]
Hi! 

Thank you for your issue notification.

Can you tell me which python and Django versions you are running the install against? Then I can setup my environment accordingly.

Thanks in advance!

**Comment by dirkmoors** [comment]
I've pushed an update which should address your problem. Could you verify if it works now?
https://pypi.python.org/pypi/django-multipleformwizard
